

# Requirement Gathering Document

## 1. Purpose

The purpose of this document is to capture the requirements for the new Python software library to map and automatically transform data from one data dictionary to another. The main dictionary we will map to is the Population Health Environmental Surveillance - Open Data Dictionary (PHES-ODM), Version 2.

## 2. Project Overview

The project involves creating a Python software library that aids in mapping data from one data dictionary to another, focusing on the Population Health Environmental Surveillance - Open Data Dictionary (PHES-ODM). This mapping and data transformation application will need to do three kinds of general mapping: 1) mapping from previous version of the PHES-ODM to the current version, 2) mapping to and from wide- and long-formats of PHES-ODM version 2, and 3) mapping from other other data formats to PHES-ODM version 2. The library should adhere to Open Science and FAIR (Findable, Accessible, Interoperable, Reusable) data principles.

## 3. Stakeholders

Stakeholders will include:
- Wastewater surveillance programs that hold data in ODM version 1.1 who want to map their data to version 2.
- Waster surveillance and laboratories that hold data in non-ODM format who want to map their data to ODM format.
- People/programs who hold data in other published dictionaries who want to map/transform their data to ODM or from ODM to their dictionary.
- People who have ODM data in wide format to wish to map their data to ODM long format. 
- Data generators/wastewater surveillance labs who want to automate transformation of raw qPCR machine outputs to the ODM.

## 4. Functional Requirements

- The library should be able to read and write PHES-ODM v2 data dictionaries.
- The library should be able to map data between PHES-ODM and other data dictionaries.
- THe library should include provisions from previous ODM-suite tools to map from raw qPCR outputs to ODM v2.
- The library should follow the FAIR data principles, ensuring that the data and the library itself are Findable, Accessible, Interoperable, and Reusable.
- The library should include functions to validate mappings against the PHES-ODM.
- The library should include documentation with clear examples of how to use the library.

## 5. Non-Functional Requirements

- The library should be implemented in Python (or R using re-code flow).
- The library should be easy to install and use.
- The library should be open source and follow open science principles.
- The library should be performant, even with large data dictionaries.
- Eventual long-term goal will be for the library to function as a web application.

# Scoping Document

## 1. Project Objective

The objective of this project is to create a Python library that aids users in mapping data from one data dictionary to another, primarily focusing on the PHES-ODM v2. The goal is not only to provide a tool for data mapping and transformation, but also to create a platform that follows open science principles and promotes the FAIR data principles.

## 2. Deliverables

The main deliverable is a Python library, along with its documentation. The library should be compatible with PHES-ODM v2 and have the ability to map to other data dictionaries, and to-and-from other data formats (ie. long-format, wide-format, qPCR output format).

## 2. File format supported

- CSV
- Excel
- PDF (for qPCR)

## 3. Types of database or dictionaries supported supported

i) ODM version to version (i.e. version 1 to version 2).
ii) ODM wide to long formats, and vice versa.
iii) Mixed ODM wide and long formats to ODM long.
iv) User generated tables to ODM (i.e. Quebec site that do not use a well-specified dictionary; rather they have generated their own in-house dictionary).
v) qPCR machine raw outputs to ODM version 2 (current capacity exists already for the following machines: AriaMx, BioRad, LightCycler, and QIAquant).
vi) Other published dictionaries or databases (specifically:
    a. [NCBI](https://www.protocols.io/run/ncbi-submission-protocol-for-sars-cov-2-wastewater-citcueiw?step=2.1)
    b. [NWSS](https://www.cdc.gov/nwss/reporting.html)
    c. [PHA4GE](https://docs.google.com/spreadsheets/d/17PuBcA0cCT-j9hV5tbwMFKtwWwKE-a_MYRqOOsIxj7c/edit#gid=136997361)
    d. [NORMAN](https://www.norman-network.com/nds/sars_cov_2/)
    e. [W-Sphere](https://sphere.waterpathogens.org/wsphere-data-template)
    f. [ENA](https://ena-docs.readthedocs.io/en/latest/submit/general-guide/metadata.html)
  The dictionaries for a-c are high priority, while d-f are lower priority. For details, please see @sec-appendix).

## 4. Out of Scope

The project will not include:

- Direct support or tools for data dictionaries other than PHES-ODM v2. While the tool should be flexible enough to handle other dictionaries, specific support for these is out of scope.
- The project won't handle data cleaning or pre-processing tasks.

## 5. Project Constraints

- The project will be completed using Python.
- The library will be built with the intent of open sourcing it.

## 6. Assumptions

- The project assumes that users have a basic understanding of Python and data dictionaries.
- It is assumed that PHES-ODM v2 is the primary dictionary to which data will be mapped.

## 7. Dependencies

- The project may depend on the ongoing maintenance and updates of the PHES-ODM v2.
- The project will follow the approach of the previously developed R package called 'recodeflow' where possible.

# Appendix {#sec-appendix}

Examples of mapping from other data dictionaries (article 3.6 of the scoping section):

*to be completed* 

## NCBI to ODM v2 

## NWSS to ODM v2

| partID	| partLabel | nwss	| nwssProcess	| nwssNotes |
|---------|-----------|-------|-------------|-----------|
| aDateEnd |	Analysis date end	| test_result_date	| SARSCOV2 Quantification results |	NA |
| aDateStart	| Analysis date start	| sample_collect_time	| sample |	NA |
| airpln	| Airplane	| airplane |	NA	| Institution_type |
| aloh3	| Aloh3 | precipitation	| concentration_method	| precessing method |	NA |
| amiconUf	| Amicon ultrafiltration	| concentration_method	| precessing method	| NA |
| beeExtractFloc	| Beef extract flocculation	| concentration_method |	precessing method |	NA |
| caRepDate	| Case report date |	test_result_date	| SARSCOV2 Quantification | results |	NA |
| ccc	| Long-term acute care hospital	| long term acute care hospital	| NA |	Institution_type |
| cdc	| Child day care |	Child day care	| NA	| Institution_type |
| centriconUf	| Centricon ultrafiltration	| concentration_method |	precessing method	NA |

## PHA4GE to ODM v2

## NORMAN to ODM v2

## w-sphere to ODM v2

## ENA to ODM v2
