name: PHES-ODM New Part Request Form
description: As a user of the ODM, we value your feedback, and if you need a new part added to the model (i.e., a new measure, method, attribute, or category), we want to be able to do that quickly and easily.
assignees:
  - mathew-thomson
title: "[New Part Request]: "
labels:
  - NPR
body:
  - type: dropdown
    id: partType
    attributes:
      label: What type of part are you wanting added?
      options:
        - measurements
        - attributes
        - methods
        - categories
        - unsure
    validations:
      required: true
  - type: input
    id: partDescr
    attributes:
      label: Please provide a brief description of the part
      placeholder: "We are measuring levels of 'geneX' from 'X organism', and so...."
    validations:
      required: true
  - type: input
    id: partID
    attributes:
      label: If you have a suggested part ID please record it here
      description: "partIDs need to be unique from all other existing part IDs, and use only alphanumeric characters. They must not start with a number, and cannot contain spaces, '-', '_', or other special characters."
    validations:
      required: false
  - type: input
    id: setInfo
    attributes:
      label: Please provide the setID for the set or sets to which this part should be added
      description: If this part is of the measurements, methods, or categories type, please state in which set(s) the part would be included.
      placeholder: "Please report the setID if you can"
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: Further comments
      description: Any additional comments, notes, or points can be added here
    validations:
      required: false
