
import pandas as pd
import numpy as np

dataset = {'AssayMethod': [{'assayMethodID': 'Assay Y100',
   'date': Timestamp('2021-01-28 00:00:00'),
   'instrumentID': 'Instrument IN200',
   'lod': 10,
   'loq': 30,
   'name': 'Assay Method Name',
   'referenceLink': 'A link to the pdf version of the SOP',
   'sampleSizeL': 0.001,
   'summary': 'Short summary assay method description',
   'unit': 'gcMl',
   'unitOther': 'gcMcovN1',
   'version': 'Assay Method Version'},
  {'assayMethodID': 'Assay Y101',
   'date': Timestamp('2021-01-29 00:00:00'),
   'instrumentID': 'Instrument IN201',
   'lod': 10,
   'loq': 30,
   'name': 'Assay Method Name',
   'referenceLink': 'A link to the pdf version of the SOP',
   'sampleSizeL': 0.001,
   'summary': 'Short summary assay method description',
   'unit': 'gcMl',
   'unitOther': 'gcMcovN1',
   'version': 'Assay Method Version'},
  {'assayMethodID': 'Assay Y102',
   'date': Timestamp('2021-01-30 00:00:00'),
   'instrumentID': 'Instrument IN202',
   'lod': 10,
   'loq': 30,
   'name': 'Assay Method Name',
   'referenceLink': 'A link to the pdf version of the SOP',
   'sampleSizeL': 0.001,
   'summary': 'Short summary assay method description',
   'unit': 'gcMl',
   'unitOther': 'gcMcovN1',
   'version': 'Assay Method Version'},
  {'assayMethodID': 'Assay Y103',
   'date': Timestamp('2021-01-31 00:00:00'),
   'instrumentID': 'Instrument IN203',
   'lod': 10,
   'loq': 30,
   'name': 'Assay Method Name',
   'referenceLink': 'A link to the pdf version of the SOP',
   'sampleSizeL': 0.001,
   'summary': 'Short summary assay method description',
   'unit': 'gcMl',
   'unitOther': 'gcMcovN2',
   'version': 'Assay Method Version'},
  {'assayMethodID': 'Assay Y104',
   'date': Timestamp('2021-02-01 00:00:00'),
   'instrumentID': 'Instrument IN204',
   'lod': 10,
   'loq': 30,
   'name': 'Assay Method Name',
   'referenceLink': 'A link to the pdf version of the SOP',
   'sampleSizeL': 0.003,
   'summary': 'Short summary assay method description',
   'unit': 'gcMl',
   'unitOther': 'gcMcovN2',
   'version': 'Assay Method Version'},
  {'assayMethodID': 'Assay Y105',
   'date': Timestamp('2021-02-02 00:00:00'),
   'instrumentID': 'Instrument IN205',
   'lod': 10,
   'loq': 30,
   'name': 'Assay Method Name',
   'referenceLink': 'A link to the pdf version of the SOP',
   'sampleSizeL': 0.002,
   'summary': 'Short summary assay method description',
   'unit': 'gcMl',
   'unitOther': 'gcMcovN2',
   'version': 'Assay Method Version'}],
 'Instrument': [{'description': 'Site Measure of flowrate',
   'instrumentID': 'Instrument IN200',
   'model': 'Instrument Model No.',
   'name': 'Instrument Name',
   'referenceLink': 'Link to Instrument IN100 specifications',
   'type': 'online',
   'typeOther': nan},
  {'description': 'Site Measure of flowrate',
   'instrumentID': 'Instrument IN201',
   'model': 'Instrument Model No.',
   'name': 'Instrument Name',
   'referenceLink': 'Link to Instrument IN100 specifications',
   'type': 'online',
   'typeOther': nan},
  {'description': 'Site Measure of flowrate',
   'instrumentID': 'Instrument IN202',
   'model': 'Instrument Model No.',
   'name': 'Instrument Name',
   'referenceLink': 'Link to Instrument IN100 specifications',
   'type': 'online',
   'typeOther': nan},
  {'description': 'Site Measure of flowrate',
   'instrumentID': 'Instrument IN203',
   'model': 'Instrument Model No.',
   'name': 'Instrument Name',
   'referenceLink': 'Link to Instrument IN100 specifications',
   'type': 'online',
   'typeOther': nan},
  {'description': 'Site Measure of flowrate',
   'instrumentID': 'Instrument IN204',
   'model': 'Instrument Model No.',
   'name': 'Instrument Name',
   'referenceLink': 'Link to Instrument IN100 specifications',
   'type': 'online',
   'typeOther': nan},
  {'description': 'Site Measure of flowrate',
   'instrumentID': 'Instrument IN205',
   'model': 'Instrument Model No.',
   'name': 'Instrument Name',
   'referenceLink': 'Link to Instrument IN100 specifications',
   'type': 'online',
   'typeOther': nan},
  {'description': 'Site Measure of flowrate',
   'instrumentID': 'Instrument IN206',
   'model': 'Instrument Model No.',
   'name': 'Instrument Name',
   'referenceLink': 'Link to Instrument IN100 specifications',
   'type': 'online',
   'typeOther': nan},
  {'description': 'Site Measure of flowrate',
   'instrumentID': 'Instrument IN207',
   'model': 'Instrument Model No.',
   'name': 'Instrument Name',
   'referenceLink': 'Link to Instrument IN100 specifications',
   'type': 'online',
   'typeOther': nan},
  {'description': 'Site Measure of flowrate',
   'instrumentID': 'Instrument IN208',
   'model': 'Instrument Model No.',
   'name': 'Instrument Name',
   'referenceLink': 'Link to Instrument IN100 specifications',
   'type': 'offline',
   'typeOther': nan}],
 'Lab': [{'assayMethodIDDefault': 'Assay Y100',
   'contactEmail': 'LabContact@Email.ca',
   'contactName': 'Lab Contact name',
   'contactPhone': '987-765-4321',
   'labID': 'Lab L100',
   'name': 'University L100 Lab',
   'updateDate': Timestamp('2021-01-28 00:00:00')},
  {'assayMethodIDDefault': 'Assay Y101',
   'contactEmail': 'LabContact@Email.ca',
   'contactName': 'Lab Contact name',
   'contactPhone': '987-765-4322',
   'labID': 'Lab L101',
   'name': 'University L100 Lab',
   'updateDate': Timestamp('2021-01-29 00:00:00')},
  {'assayMethodIDDefault': 'Assay Y102',
   'contactEmail': 'LabContact@Email.ca',
   'contactName': 'Lab Contact name',
   'contactPhone': '987-765-4323',
   'labID': 'Lab L102',
   'name': 'University L100 Lab',
   'updateDate': Timestamp('2021-01-30 00:00:00')},
  {'assayMethodIDDefault': 'Assay Y103',
   'contactEmail': 'LabContact@Email.ca',
   'contactName': 'Lab Contact name',
   'contactPhone': '987-765-4324',
   'labID': 'Lab L103',
   'name': 'University L100 Lab',
   'updateDate': Timestamp('2021-01-31 00:00:00')},
  {'assayMethodIDDefault': 'Assay Y104',
   'contactEmail': 'LabContact@Email.ca',
   'contactName': 'Lab Contact name',
   'contactPhone': '987-765-4325',
   'labID': 'Lab L104',
   'name': 'University L100 Lab',
   'updateDate': Timestamp('2021-02-01 00:00:00')},
  {'assayMethodIDDefault': 'Assay Y105',
   'contactEmail': 'LabContact@Email.ca',
   'contactName': 'Lab Contact name',
   'contactPhone': '987-765-4326',
   'labID': 'Lab L105',
   'name': 'University L100 Lab',
   'updateDate': Timestamp('2021-02-02 00:00:00')},
  {'assayMethodIDDefault': 'Assay Y106',
   'contactEmail': 'LabContact@Email.ca',
   'contactName': 'Lab Contact name',
   'contactPhone': '987-765-4327',
   'labID': 'Lab L106',
   'name': 'University L100 Lab',
   'updateDate': Timestamp('2021-02-03 00:00:00')},
  {'assayMethodIDDefault': 'Assay Y107',
   'contactEmail': 'LabContact@Email.ca',
   'contactName': 'Lab Contact name',
   'contactPhone': '987-765-4328',
   'labID': 'Lab L107',
   'name': 'University L100 Lab',
   'updateDate': Timestamp('2021-02-04 00:00:00')},
  {'assayMethodIDDefault': 'Assay Y108',
   'contactEmail': 'LabContact@Email.ca',
   'contactName': 'Lab Contact name',
   'contactPhone': '987-765-4329',
   'labID': 'Lab L108',
   'name': 'University L100 Lab',
   'updateDate': Timestamp('2021-02-05 00:00:00')},
  {'assayMethodIDDefault': 'Assay Y109',
   'contactEmail': 'LabContact@Email.ca',
   'contactName': 'Lab Contact name',
   'contactPhone': '987-765-4330',
   'labID': 'Lab L109',
   'name': 'University L100 Lab',
   'updateDate': Timestamp('2021-02-06 00:00:00')},
  {'assayMethodIDDefault': 'Assay Y110',
   'contactEmail': 'LabContact@Email.ca',
   'contactName': 'Lab Contact name',
   'contactPhone': '987-765-4331',
   'labID': 'Lab L110',
   'name': 'University L100 Lab',
   'updateDate': Timestamp('2021-02-07 00:00:00')},
  {'assayMethodIDDefault': 'Assay Y111',
   'contactEmail': 'LabContact@Email.ca',
   'contactName': 'Lab Contact name',
   'contactPhone': '987-765-4332',
   'labID': 'Lab L111',
   'name': 'University L101 Lab',
   'updateDate': Timestamp('2021-02-08 00:00:00')}],
 'Reporter': [{'contactEmail': 'ReporterR1@email.ca',
   'contactName': 'ReporterName',
   'contactPhone': '123-456-7890',
   'labIDDefault': 'Lab L100',
   'notes': "I'm responsible for reporting the data and metadata",
   'reporterID': 'Reporter R1',
   'siteIDDefault': 'Site T100'},
  {'contactEmail': 'ReporterR1@email.ca',
   'contactName': 'ReporterName',
   'contactPhone': '123-456-7891',
   'labIDDefault': 'Lab L101',
   'notes': "I'm responsible for reporting the data and metadata",
   'reporterID': 'Reporter R2',
   'siteIDDefault': 'Site T101'},
  {'contactEmail': 'ReporterR1@email.ca',
   'contactName': 'ReporterName',
   'contactPhone': '123-456-7892',
   'labIDDefault': 'Lab L102',
   'notes': "I'm responsible for reporting the data and metadata",
   'reporterID': 'Reporter R3',
   'siteIDDefault': 'Site T102'},
  {'contactEmail': 'ReporterR1@email.ca',
   'contactName': 'ReporterName',
   'contactPhone': '123-456-7893',
   'labIDDefault': 'Lab L103',
   'notes': "I'm responsible for reporting the data and metadata",
   'reporterID': 'Reporter R4',
   'siteIDDefault': 'Site T103'},
  {'contactEmail': 'ReporterR1@email.ca',
   'contactName': 'ReporterName',
   'contactPhone': '123-456-7894',
   'labIDDefault': 'Lab L104',
   'notes': "I'm responsible for reporting the data and metadata",
   'reporterID': 'Reporter R5',
   'siteIDDefault': 'Site T104'},
  {'contactEmail': 'ReporterR1@email.ca',
   'contactName': 'ReporterName',
   'contactPhone': '123-456-7895',
   'labIDDefault': 'Lab L105',
   'notes': "I'm responsible for reporting the data and metadata",
   'reporterID': 'Reporter R6',
   'siteIDDefault': 'Site T105'},
  {'contactEmail': 'ReporterR1@email.ca',
   'contactName': 'ReporterName',
   'contactPhone': '123-456-7896',
   'labIDDefault': 'Lab L106',
   'notes': "I'm responsible for reporting the data and metadata",
   'reporterID': 'Reporter R7',
   'siteIDDefault': 'Site T106'},
  {'contactEmail': 'ReporterR1@email.ca',
   'contactName': 'ReporterName',
   'contactPhone': '123-456-7897',
   'labIDDefault': 'Lab L107',
   'notes': "I'm responsible for reporting the data and metadata",
   'reporterID': 'Reporter R8',
   'siteIDDefault': 'Site T107'},
  {'contactEmail': 'ReporterR1@email.ca',
   'contactName': 'ReporterName',
   'contactPhone': '123-456-7898',
   'labIDDefault': 'Lab L108',
   'notes': "I'm responsible for reporting the data and metadata",
   'reporterID': 'Reporter R9',
   'siteIDDefault': 'Site T108'},
  {'contactEmail': 'ReporterR1@email.ca',
   'contactName': 'ReporterName',
   'contactPhone': '123-456-7899',
   'labIDDefault': 'Lab L109',
   'notes': "I'm responsible for reporting the data and metadata",
   'reporterID': 'Reporter R10',
   'siteIDDefault': 'Site T109'},
  {'contactEmail': 'ReporterR1@email.ca',
   'contactName': 'ReporterName',
   'contactPhone': '123-456-7900',
   'labIDDefault': 'Lab L110',
   'notes': "I'm responsible for reporting the data and metadata",
   'reporterID': 'Reporter R11',
   'siteIDDefault': 'Site T110'}],
 'Sample': [{'collection': 'cpTP24h',
   'dateTime': Timestamp('2021-02-01 21:00:00'),
   'dateTimeEnd': Timestamp('2021-02-01 21:00:00'),
   'dateTimeStart': Timestamp('2021-02-01 21:00:00'),
   'fieldSampleTempC': 15,
   'notes': 'Samples shipped on ice from site to lab by courier',
   'sampleID': 'Sample S100',
   'shippedOnce': 'Yes',
   'siteID': 'Site T100',
   'sizeL': 2,
   'storageTempC': 16,
   'type': 'rawWW'},
  {'collection': 'cpTP24h',
   'dateTime': Timestamp('2021-02-01 21:00:00'),
   'dateTimeEnd': Timestamp('2021-02-01 21:00:00'),
   'dateTimeStart': Timestamp('2021-02-01 21:00:00'),
   'fieldSampleTempC': 15,
   'notes': 'Samples shipped on ice from site to lab by courier',
   'sampleID': 'Sample S101',
   'shippedOnce': 'Yes',
   'siteID': 'Site T101',
   'sizeL': 2,
   'storageTempC': 16,
   'type': 'rawWW'},
  {'collection': 'cpTP24h',
   'dateTime': Timestamp('2021-02-01 21:00:00'),
   'dateTimeEnd': Timestamp('2021-02-01 21:00:00'),
   'dateTimeStart': Timestamp('2021-02-01 21:00:00'),
   'fieldSampleTempC': 15,
   'notes': 'Samples shipped on ice from site to lab by courier',
   'sampleID': 'Sample S102',
   'shippedOnce': 'Yes',
   'siteID': 'Site T102',
   'sizeL': 2,
   'storageTempC': 16,
   'type': 'rawWW'},
  {'collection': 'cpTP24h',
   'dateTime': Timestamp('2021-02-01 21:00:00'),
   'dateTimeEnd': Timestamp('2021-02-04 21:00:00'),
   'dateTimeStart': Timestamp('2021-02-03 21:00:00'),
   'fieldSampleTempC': 15,
   'notes': 'Samples shipped on ice from site to lab by courier',
   'sampleID': 'Sample S103',
   'shippedOnce': 'Yes',
   'siteID': 'Site T103',
   'sizeL': 2,
   'storageTempC': 25,
   'type': 'rawWW'},
  {'collection': 'cpTP24h',
   'dateTime': Timestamp('2021-02-01 21:00:00'),
   'dateTimeEnd': Timestamp('2021-02-03 21:00:00'),
   'dateTimeStart': Timestamp('2021-02-02 21:00:00'),
   'fieldSampleTempC': 15,
   'notes': 'Samples shipped on ice from site to lab by courier',
   'sampleID': 'Sample S104',
   'shippedOnce': 'Yes',
   'siteID': 'Site T104',
   'sizeL': 1,
   'storageTempC': 16,
   'type': 'rawWW'},
  {'collection': 'cpTP24h',
   'dateTime': Timestamp('2021-02-01 21:00:00'),
   'dateTimeEnd': Timestamp('2021-02-02 21:00:00'),
   'dateTimeStart': Timestamp('2021-02-01 21:00:00'),
   'fieldSampleTempC': 17,
   'notes': 'Samples shipped on ice from site to lab by courier',
   'sampleID': 'Sample S105',
   'shippedOnce': 'Yes',
   'siteID': 'Site T105',
   'sizeL': 2,
   'storageTempC': 22,
   'type': 'rawWW'},
  {'collection': 'cpTP24h',
   'dateTime': Timestamp('2021-01-25 21:00:00'),
   'dateTimeEnd': Timestamp('2021-01-24 08:00:00'),
   'dateTimeStart': Timestamp('2021-01-24 08:00:00'),
   'fieldSampleTempC': 17,
   'notes': 'Samples shipped on ice from site to lab by courier',
   'sampleID': 'Sample S106',
   'shippedOnce': 'Yes',
   'siteID': 'Site T106',
   'sizeL': 2,
   'storageTempC': 16,
   'type': 'rawWW'},
  {'collection': 'cpTP24h',
   'dateTime': Timestamp('2021-01-28 21:00:00'),
   'dateTimeEnd': Timestamp('2021-01-27 08:00:00'),
   'dateTimeStart': Timestamp('2021-01-27 08:00:00'),
   'fieldSampleTempC': 18,
   'notes': 'Samples shipped on ice from site to lab by courier',
   'sampleID': 'Sample S107',
   'shippedOnce': 'Yes',
   'siteID': 'Site T107',
   'sizeL': 2,
   'storageTempC': 16,
   'type': 'rawWW'},
  {'collection': 'cpTP24h',
   'dateTime': Timestamp('2021-01-26 21:00:00'),
   'dateTimeEnd': Timestamp('2021-01-25 08:00:00'),
   'dateTimeStart': Timestamp('2021-01-25 08:00:00'),
   'fieldSampleTempC': 18,
   'notes': 'Samples shipped on ice from site to lab by courier',
   'sampleID': 'Sample S108',
   'shippedOnce': 'Yes',
   'siteID': 'Site T108',
   'sizeL': 2,
   'storageTempC': 18,
   'type': 'rawWW'},
  {'collection': 'grb',
   'dateTime': Timestamp('2021-01-29 21:00:00'),
   'dateTimeEnd': Timestamp('2021-01-28 08:00:00'),
   'dateTimeStart': Timestamp('2021-01-28 08:00:00'),
   'fieldSampleTempC': 14,
   'notes': 'Samples shipped on ice from site to lab by courier',
   'sampleID': 'Sample S109',
   'shippedOnce': 'Yes',
   'siteID': 'Site T109',
   'sizeL': 2,
   'storageTempC': 16,
   'type': 'rawWW'},
  {'collection': 'cpTP24h',
   'dateTime': Timestamp('2021-01-31 21:00:00'),
   'dateTimeEnd': Timestamp('2021-01-30 08:00:00'),
   'dateTimeStart': Timestamp('2021-01-30 08:00:00'),
   'fieldSampleTempC': 13,
   'notes': 'Samples shipped on ice from site to lab by courier',
   'sampleID': 'Sample S110',
   'shippedOnce': 'Yes',
   'siteID': 'Site T110',
   'sizeL': 3,
   'storageTempC': 17,
   'type': 'water'},
  {'collection': 'mooreSw',
   'dateTime': Timestamp('2021-02-27 21:00:00'),
   'dateTimeEnd': Timestamp('2021-01-26 08:00:00'),
   'dateTimeStart': Timestamp('2021-01-26 08:00:00'),
   'fieldSampleTempC': 12,
   'notes': 'Samples shipped on ice from site to lab by courier',
   'sampleID': 'Sample S111',
   'shippedOnce': 'Yes',
   'siteID': 'Site T111',
   'sizeL': 4,
   'storageTempC': 16,
   'type': 'rawWW'},
  {'collection': 'cpTP24h',
   'dateTime': Timestamp('2021-02-26 21:00:00'),
   'dateTimeEnd': Timestamp('2021-01-26 08:00:00'),
   'dateTimeStart': Timestamp('2021-01-26 08:00:00'),
   'fieldSampleTempC': 16,
   'notes': 'Samples shipped on ice from site to lab by courier',
   'sampleID': 'Sample S112',
   'shippedOnce': 'No',
   'siteID': 'Site T112',
   'sizeL': 8,
   'storageTempC': 19,
   'type': 'pSludge'},
  {'collection': 'cpTP24h',
   'dateTime': Timestamp('2021-02-01 21:00:00'),
   'dateTimeEnd': Timestamp('2021-01-24 08:00:00'),
   'dateTimeStart': Timestamp('2021-01-26 08:00:00'),
   'fieldSampleTempC': 16,
   'notes': 'Samples shipped on ice from site to lab by courier',
   'sampleID': 'Sample S113',
   'shippedOnce': 'Yes',
   'siteID': 'Site T113',
   'sizeL': 10,
   'storageTempC': 20,
   'type': 'swrSed'}],
 'Site': [{'description': 'City of Toronto WWTP',
   'geoLat': 43.7668287,
   'geoLong': -79.1507006,
   'name': 'Highland Creek WWTP',
   'notes': 'WWTP experiences peak flows during storm events due to inflow',
   'siteID': 'Site T100',
   'type': 'wwtpMuS',
   'typeOther': nan},
  {'description': 'City of Toronto WWTP',
   'geoLat': 43.7668287,
   'geoLong': -79.1507006,
   'name': 'Highland Creek WWTP',
   'notes': 'WWTP experiences peak flows during storm events due to inflow',
   'siteID': 'Site T101',
   'type': 'wwtpMuS',
   'typeOther': nan},
  {'description': 'City of Toronto WWTP',
   'geoLat': 43.7668287,
   'geoLong': -79.1507006,
   'name': 'Highland Creek WWTP',
   'notes': 'WWTP experiences peak flows during storm events due to inflow',
   'siteID': 'Site T102',
   'type': 'wwtpMuS',
   'typeOther': nan},
  {'description': 'City of Toronto WWTP',
   'geoLat': 43.7668287,
   'geoLong': -79.1507006,
   'name': 'Highland Creek WWTP',
   'notes': 'WWTP experiences peak flows during storm events due to inflow',
   'siteID': 'Site T103',
   'type': 'wwtpMuS',
   'typeOther': nan},
  {'description': 'City of Toronto WWTP',
   'geoLat': 43.7668287,
   'geoLong': -79.1507006,
   'name': 'Highland Creek WWTP',
   'notes': 'WWTP experiences peak flows during storm events due to inflow',
   'siteID': 'Site T104',
   'type': 'wwtpMuS',
   'typeOther': nan},
  {'description': 'City of Toronto WWTP',
   'geoLat': 43.7668287,
   'geoLong': -79.1507006,
   'name': 'Highland Creek WWTP',
   'notes': 'WWTP experiences peak flows during storm events due to inflow',
   'siteID': 'Site T105',
   'type': 'wwtpMuS',
   'typeOther': nan},
  {'description': 'City of Toronto WWTP',
   'geoLat': 43.7668287,
   'geoLong': -79.1507006,
   'name': 'Highland Creek WWTP',
   'notes': 'WWTP experiences peak flows during storm events due to inflow',
   'siteID': 'Site T106',
   'type': 'wwtpMuS',
   'typeOther': nan},
  {'description': 'City of Toronto WWTP',
   'geoLat': 43.7668287,
   'geoLong': -79.1507006,
   'name': 'Highland Creek WWTP',
   'notes': 'WWTP experiences peak flows during storm events due to inflow',
   'siteID': 'Site T107',
   'type': 'wwtpMuS',
   'typeOther': nan},
  {'description': 'City of Toronto WWTP',
   'geoLat': 44.7668287,
   'geoLong': -79.1507006,
   'name': 'Highland Creek WWTP',
   'notes': 'WWTP experiences peak flows during storm events due to inflow',
   'siteID': 'Site T108',
   'type': 'wwtpMuC',
   'typeOther': nan}],
 'SiteMeasure': [{'aggregation': 'mean',
   'aggregationDesc': 'WWTP flow meter',
   'aggregationOther': nan,
   'dateTime': Timestamp('2021-01-27 18:00:00'),
   'instrumentID': 'Instrument IN200',
   'notes': 'The field sampling and flow measurement presented no field issues',
   'reporterID': 'Reporter R1',
   'sampleID': 'Sample S100',
   'siteID': 'Site T100',
   'type': 'wwFlow',
   'typeDescription': 'Measured daily average flow',
   'typeOther': nan,
   'uSiteMeasureID': 'Site Measure S100_T100_AF100',
   'unit': 'MGPD',
   'value': 58},
  {'aggregation': 'max',
   'aggregationDesc': 'Field hand held probe',
   'aggregationOther': nan,
   'dateTime': Timestamp('2021-01-27 12:00:00'),
   'instrumentID': 'Instrument IN200',
   'notes': 'The field hand-held T-probe was calibrated in the lab',
   'reporterID': 'Reporter R1',
   'sampleID': 'Sample S100',
   'siteID': 'Site T100',
   'type': 'wwpH',
   'typeDescription': 'Field hand-held temperature probe',
   'typeOther': nan,
   'uSiteMeasureID': 'Site Measure S100_T100_AT100',
   'unit': 'oC',
   'value': 15},
  {'aggregation': 'max',
   'aggregationDesc': 'Field hand held probe',
   'aggregationOther': nan,
   'dateTime': Timestamp('2021-01-28 12:00:00'),
   'instrumentID': 'Instrument IN201',
   'notes': 'The field hand-held T-probe was calibrated in the lab',
   'reporterID': 'Reporter R2',
   'sampleID': 'Sample S101',
   'siteID': 'Site T101',
   'type': 'wwpH',
   'typeDescription': 'Field hand-held temperature probe',
   'typeOther': nan,
   'uSiteMeasureID': 'Site Measure S100_T100_AT101',
   'unit': 'oC',
   'value': 16},
  {'aggregation': 'max',
   'aggregationDesc': 'Field hand held probe',
   'aggregationOther': nan,
   'dateTime': Timestamp('2021-01-29 12:00:00'),
   'instrumentID': 'Instrument IN202',
   'notes': 'The field hand-held T-probe was calibrated in the lab',
   'reporterID': 'Reporter R3',
   'sampleID': 'Sample S102',
   'siteID': 'Site T102',
   'type': 'wwpH',
   'typeDescription': 'Field hand-held temperature probe',
   'typeOther': nan,
   'uSiteMeasureID': 'Site Measure S100_T100_AT102',
   'unit': 'oC',
   'value': 17},
  {'aggregation': 'max',
   'aggregationDesc': 'Field hand held probe',
   'aggregationOther': nan,
   'dateTime': Timestamp('2021-01-30 12:00:00'),
   'instrumentID': 'Instrument IN203',
   'notes': 'The field hand-held T-probe was calibrated in the lab',
   'reporterID': 'Reporter R4',
   'sampleID': 'Sample S103',
   'siteID': 'Site T103',
   'type': 'wwpH',
   'typeDescription': 'Field hand-held temperature probe',
   'typeOther': nan,
   'uSiteMeasureID': 'Site Measure S100_T100_AT103',
   'unit': 'oC',
   'value': 18},
  {'aggregation': 'max',
   'aggregationDesc': 'Field hand held probe',
   'aggregationOther': nan,
   'dateTime': Timestamp('2021-01-31 12:00:00'),
   'instrumentID': 'Instrument IN204',
   'notes': 'The field hand-held T-probe was calibrated in the lab',
   'reporterID': 'Reporter R5',
   'sampleID': 'Sample S104',
   'siteID': 'Site T104',
   'type': 'wwpH',
   'typeDescription': 'Field hand-held temperature probe',
   'typeOther': nan,
   'uSiteMeasureID': 'Site Measure S100_T100_AT104',
   'unit': 'oC',
   'value': 19},
  {'aggregation': 'max',
   'aggregationDesc': 'Field hand held probe',
   'aggregationOther': nan,
   'dateTime': Timestamp('2021-02-01 12:00:00'),
   'instrumentID': 'Instrument IN205',
   'notes': 'The field hand-held T-probe was calibrated in the lab',
   'reporterID': 'Reporter R6',
   'sampleID': 'Sample S105',
   'siteID': 'Site T105',
   'type': 'wwpH',
   'typeDescription': 'Field hand-held temperature probe',
   'typeOther': nan,
   'uSiteMeasureID': 'Site Measure S100_T100_AT105',
   'unit': 'oC',
   'value': 20},
  {'aggregation': 'max',
   'aggregationDesc': 'Field hand held probe',
   'aggregationOther': nan,
   'dateTime': Timestamp('2021-02-02 12:00:00'),
   'instrumentID': 'Instrument IN206',
   'notes': 'The field hand-held T-probe was calibrated in the lab',
   'reporterID': 'Reporter R7',
   'sampleID': 'Sample S106',
   'siteID': 'Site T106',
   'type': 'wwpH',
   'typeDescription': 'Field hand-held temperature probe',
   'typeOther': nan,
   'uSiteMeasureID': 'Site Measure S100_T100_AT106',
   'unit': 'oC',
   'value': 21},
  {'aggregation': 'max',
   'aggregationDesc': 'Field hand held probe',
   'aggregationOther': nan,
   'dateTime': Timestamp('2021-02-03 12:00:00'),
   'instrumentID': 'Instrument IN207',
   'notes': 'The field hand-held T-probe was calibrated in the lab',
   'reporterID': 'Reporter R8',
   'sampleID': 'Sample S107',
   'siteID': 'Site T107',
   'type': 'wwpH1',
   'typeDescription': 'Field hand-held temperature probe',
   'typeOther': nan,
   'uSiteMeasureID': 'Site Measure S100_T100_AT107',
   'unit': 'oC',
   'value': 22}],
 'WWMeasure': [{'analysisDate': Timestamp('2021-02-08 00:00:00'),
   'assayID': 'Assay Y100',
   'fractionAnalyzed': 'solid',
   'index': 1,
   'instrumentID': 'Instrument IN200',
   'labID': 'Lab L100',
   'notes': 'CovidN1 replicate measures linked by index',
   'reportDate': Timestamp('2021-01-25 00:00:00'),
   'reporterID': 'Reporter R1',
   'sampleID': 'Sample S100',
   'type': 'covN1',
   'typeOther': nan,
   'uWwMeasureID': 'Measure WW100',
   'unit': 'gcM',
   'unitOther': 'gcMcovN1',
   'value': 20000},
  {'analysisDate': Timestamp('2021-03-31 00:00:00'),
   'assayID': 'Assay Y100',
   'fractionAnalyzed': 'solid',
   'index': 2,
   'instrumentID': 'Instrument IN200',
   'labID': 'Lab L100',
   'notes': 'CovidN1 replicate measures linked by index',
   'reportDate': Timestamp('2021-01-25 00:00:00'),
   'reporterID': 'Reporter R1',
   'sampleID': 'Sample S100',
   'type': 'covN1',
   'typeOther': nan,
   'uWwMeasureID': 'Measure WW100',
   'unit': 'gcMl',
   'unitOther': 'gcMcovN1',
   'value': 22000},
  {'analysisDate': Timestamp('2021-03-29 00:00:00'),
   'assayID': 'Assay Y100',
   'fractionAnalyzed': 'solid',
   'index': 3,
   'instrumentID': 'Instrument IN200',
   'labID': 'Lab L100',
   'notes': 'CovidN1 replicate measures linked by index',
   'reportDate': Timestamp('2021-01-26 00:00:00'),
   'reporterID': 'Reporter R1',
   'sampleID': 'Sample S100',
   'type': 'covN1',
   'typeOther': nan,
   'uWwMeasureID': 'Measure WW100',
   'unit': 'gcMl',
   'unitOther': 'gcMcovN1',
   'value': 23000},
  {'analysisDate': Timestamp('2021-01-25 00:00:00'),
   'assayID': 'Assay Y100',
   'fractionAnalyzed': 'solid',
   'index': 4,
   'instrumentID': 'Instrument IN200',
   'labID': 'Lab L100',
   'notes': 'CovidN2 replicate measures linked by index',
   'reportDate': Timestamp('2021-02-06 00:00:00'),
   'reporterID': 'Reporter R1',
   'sampleID': 'Sample S100',
   'type': 'covN2',
   'typeOther': nan,
   'uWwMeasureID': 'Measure WW100',
   'unit': 'gcMl',
   'unitOther': 'gcMcovN2',
   'value': 15000},
  {'analysisDate': Timestamp('2021-01-28 00:00:00'),
   'assayID': 'Assay Y100',
   'fractionAnalyzed': 'solid',
   'index': 5,
   'instrumentID': 'Instrument IN200',
   'labID': 'Lab L100',
   'notes': 'CovidN2 replicate measures linked by index',
   'reportDate': Timestamp('2021-01-25 00:00:00'),
   'reporterID': 'Reporter R1',
   'sampleID': 'Sample S100',
   'type': 'covN2',
   'typeOther': nan,
   'uWwMeasureID': 'Measure WW100',
   'unit': 'gcMl',
   'unitOther': 'gcMcovN2',
   'value': 16000},
  {'analysisDate': Timestamp('2021-01-27 00:00:00'),
   'assayID': 'Assay Y100',
   'fractionAnalyzed': 'solid',
   'index': 6,
   'instrumentID': 'Instrument IN200',
   'labID': 'Lab L100',
   'notes': 'CovidN2 replicate measures linked by index',
   'reportDate': Timestamp('2021-01-26 00:00:00'),
   'reporterID': 'Reporter R1',
   'sampleID': 'Sample S100',
   'type': 'covN2',
   'typeOther': nan,
   'uWwMeasureID': 'Measure WW100',
   'unit': 'gcMl',
   'unitOther': 'gcMcovN2',
   'value': 17000},
  {'analysisDate': Timestamp('2021-01-29 00:00:00'),
   'assayID': 'Assay Y100',
   'fractionAnalyzed': 'solid',
   'index': 1,
   'instrumentID': 'Instrument IN200',
   'labID': 'Lab L100',
   'notes': 'nPMMoV measure linked to CovidN1 by index',
   'reportDate': Timestamp('2021-03-06 00:00:00'),
   'reporterID': 'Reporter R1',
   'sampleID': 'Sample S100',
   'type': 'nPMMoV',
   'typeOther': nan,
   'uWwMeasureID': 'Measure WW100',
   'unit': 'gcMl',
   'unitOther': 'gcmnPMMoV',
   'value': 80000},
  {'analysisDate': Timestamp('2021-03-06 00:00:00'),
   'assayID': 'Assay Y100',
   'fractionAnalyzed': 'solid',
   'index': 2,
   'instrumentID': 'Instrument IN200',
   'labID': 'Lab L100',
   'notes': 'nPMMoV measure linked to CovidN1 by index',
   'reportDate': Timestamp('2021-01-26 00:00:00'),
   'reporterID': 'Reporter R1',
   'sampleID': 'Sample S100',
   'type': 'nPMMoV',
   'typeOther': nan,
   'uWwMeasureID': 'Measure WW100',
   'unit': 'gcMl',
   'unitOther': 'gcmnPMMoV',
   'value': 82000},
  {'analysisDate': Timestamp('2021-02-07 00:00:00'),
   'assayID': 'Assay Y100',
   'fractionAnalyzed': 'solid',
   'index': 3,
   'instrumentID': 'Instrument IN200',
   'labID': 'Lab L100',
   'notes': 'nPMMoV measure linked to CovidN1 by index',
   'reportDate': Timestamp('2021-01-28 00:00:00'),
   'reporterID': 'Reporter R1',
   'sampleID': 'Sample S100',
   'type': 'nPMMoV',
   'typeOther': nan,
   'uWwMeasureID': 'Measure WW100',
   'unit': 'gcMl',
   'unitOther': 'gcmnPMMoV',
   'value': 85000},
  {'analysisDate': Timestamp('2021-01-31 00:00:00'),
   'assayID': 'Assay Y100',
   'fractionAnalyzed': 'solid',
   'index': 4,
   'instrumentID': 'Instrument IN200',
   'labID': 'Lab L100',
   'notes': 'nPMMoV measure linked to CovidN2 by index',
   'reportDate': Timestamp('2021-02-02 00:00:00'),
   'reporterID': 'Reporter R1',
   'sampleID': 'Sample S100',
   'type': 'nPMMoV',
   'typeOther': nan,
   'uWwMeasureID': 'Measure WW100',
   'unit': 'gcMl',
   'unitOther': 'gcmnPMMoV',
   'value': 75000},
  {'analysisDate': Timestamp('2021-02-09 00:00:00'),
   'assayID': 'Assay Y100',
   'fractionAnalyzed': 'solid',
   'index': 5,
   'instrumentID': 'Instrument IN200',
   'labID': 'Lab L100',
   'notes': 'nPMMoV measure linked to CovidN2 by index',
   'reportDate': Timestamp('2021-02-02 00:00:00'),
   'reporterID': 'Reporter R1',
   'sampleID': 'Sample S100',
   'type': 'nPMMoV',
   'typeOther': nan,
   'uWwMeasureID': 'Measure WW100',
   'unit': 'gcMl',
   'unitOther': 'gcmnPMMoV',
   'value': 76000},
  {'analysisDate': Timestamp('2021-02-02 00:00:00'),
   'assayID': 'Assay Y100',
   'fractionAnalyzed': 'solid',
   'index': 1,
   'instrumentID': 'Instrument IN200',
   'labID': 'Lab L100',
   'notes': 'nPMMoV measure linked to CovidN2 by index',
   'reportDate': Timestamp('2021-02-06 00:00:00'),
   'reporterID': 'Reporter R1',
   'sampleID': 'Sample S100',
   'type': 'nPMMoV',
   'typeOther': nan,
   'uWwMeasureID': 'Measure WW100',
   'unit': 'gcMl',
   'unitOther': 'gcmnPMMoV',
   'value': 72000},
  {'analysisDate': Timestamp('2021-02-25 00:00:00'),
   'assayID': 'Assay Y101',
   'fractionAnalyzed': 'solid',
   'index': 6,
   'instrumentID': 'Instrument IN201',
   'labID': 'Lab L101',
   'notes': 'nPMMoV measure linked to CovidN2 by index',
   'reportDate': Timestamp('2021-02-09 00:00:00'),
   'reporterID': 'Reporter R2',
   'sampleID': 'Sample S101',
   'type': 'nPMMoV',
   'typeOther': nan,
   'uWwMeasureID': 'Measure WW101',
   'unit': 'gcMl',
   'unitOther': 'gcmnPMMoV',
   'value': 72000},
  {'analysisDate': Timestamp('2021-03-25 00:00:00'),
   'assayID': 'Assay Y102',
   'fractionAnalyzed': 'solid',
   'index': 6,
   'instrumentID': 'Instrument IN202',
   'labID': 'Lab L102',
   'notes': 'nPMMoV measure linked to CovidN2 by index',
   'reportDate': Timestamp('2021-01-30 00:00:00'),
   'reporterID': 'Reporter R3',
   'sampleID': 'Sample S102',
   'type': 'nPMMoV',
   'typeOther': nan,
   'uWwMeasureID': 'Measure WW102',
   'unit': 'gcMl',
   'unitOther': 'gcmnPMMoV',
   'value': 72000},
  {'analysisDate': Timestamp('2021-01-26 00:00:00'),
   'assayID': 'Assay Y103',
   'fractionAnalyzed': 'liquid',
   'index': 2,
   'instrumentID': 'Instrument IN203',
   'labID': 'Lab L103',
   'notes': 'nPMMoV measure linked to CovidN2 by index',
   'reportDate': Timestamp('2021-01-26 00:00:00'),
   'reporterID': 'Reporter R4',
   'sampleID': 'Sample S103',
   'type': 'nPMMoV',
   'typeOther': nan,
   'uWwMeasureID': 'Measure WW103',
   'unit': 'gcMl',
   'unitOther': 'gcmnPMMoV',
   'value': 92000},
  {'analysisDate': Timestamp('2021-01-28 00:00:00'),
   'assayID': 'Assay Y104',
   'fractionAnalyzed': 'solid',
   'index': 2,
   'instrumentID': 'Instrument IN204',
   'labID': 'Lab L104',
   'notes': 'nPMMoV measure linked to CovidN2 by index',
   'reportDate': Timestamp('2021-01-26 00:00:00'),
   'reporterID': 'Reporter R5',
   'sampleID': 'Sample S104',
   'type': 'nPMMoV',
   'typeOther': nan,
   'uWwMeasureID': 'Measure WW104',
   'unit': 'gcMl',
   'unitOther': 'gcmnPMMoV',
   'value': 102000},
  {'analysisDate': Timestamp('2021-02-26 00:00:00'),
   'assayID': 'Assay Y105',
   'fractionAnalyzed': 'solid',
   'index': 6,
   'instrumentID': 'Instrument IN205',
   'labID': 'Lab L105',
   'notes': 'nPMMoV measure linked to CovidN2 by index6',
   'reportDate': Timestamp('2021-01-31 00:00:00'),
   'reporterID': 'Reporter R6',
   'sampleID': 'Sample S105',
   'type': 'nPMMoV',
   'typeOther': nan,
   'uWwMeasureID': 'Measure WW105',
   'unit': 'gcMl',
   'unitOther': 'gcmnPMMoV',
   'value': 145000},
  {'analysisDate': Timestamp('2021-02-25 00:00:00'),
   'assayID': 'Assay Y106',
   'fractionAnalyzed': 'solid',
   'index': 2,
   'instrumentID': 'Instrument IN206',
   'labID': 'Lab L106',
   'notes': 'nPMMoV measure linked to CovidN2 by index',
   'reportDate': Timestamp('2021-01-25 00:00:00'),
   'reporterID': 'Reporter R7',
   'sampleID': 'Sample S106',
   'type': 'nPMMoV1',
   'typeOther': nan,
   'uWwMeasureID': 'Measure WW106',
   'unit': 'gcM',
   'unitOther': 'gcmnPMMoV1',
   'value': 89000},
  {'analysisDate': Timestamp('2021-02-08 00:00:00'),
   'assayID': 'Assay Y107',
   'fractionAnalyzed': 'solid',
   'index': 6,
   'instrumentID': 'Instrument IN207',
   'labID': 'Lab L107',
   'notes': 'nPMMoV measure linked to CovidN2 by index',
   'reportDate': Timestamp('2021-01-26 00:00:00'),
   'reporterID': 'Reporter R8',
   'sampleID': 'Sample S107',
   'type': 'nPMMoV',
   'typeOther': nan,
   'uWwMeasureID': 'Measure WW107',
   'unit': 'gcMl',
   'unitOther': 'gcmnPMMoV',
   'value': 98000}]}

organization = "PHAC"

def create_dataset(rule,data=dataset, org= organization):
  """The function takes in data in form of a dictionary where the keys specify each table in the data and the value is the actual data in the
  form of list of dictionaries where each nested dictionary is a row within the table. The function also takes in as input the rule which is
  a list of dictionaries where each dictionary specifies the sharing properties such as organization, rulesValue, entities such as table
  and variables to which a particular ruleValue corresponds to. The function finally outputs a list with two dictionaries. One of the dictionary 
  is the filtered dataset and the other dictionary contains the entities filtered i.e. the rows or the columns removed along with the 
  ruleid and the table name.
  """



  return [{},{}]