@startuml

header

header

endheader

start

while (there is more data)

  if (First Iff) then (yes)

   if (Second if) then (yes)

if (Third if) then (yes)

:add to list;

if(another condition) then (no)

else(yes)

end

endif

endif

endif

:do something;

endif

endwhile

end

@enduml