@startuml sequencediagram

actor DataCustodian as USER
USER -> WebApp: Enter names of tables in a list
USER -> WebApp: Input data to filter
USER -> WebApp: Enter names of organizations to share data with
USER -> WebApp: Input schema file
WebApp -> EntityRelationFilter: Send data to filter based on primary and foreign key relationship
WebApp -> CreateSchemaDictionary: Send schema file to create a json like dictionary from schema file
CreateSchemaDictionary -> FilterEntities: send schema dictionary to filter columns/ variables
EntityRelationFilter -> FilterEntities: send filtered data to further filter on columns/ variables
CreateSchemaDictionary -> FilterRows: send schema dictionary to filter rows
EntityRelationFilter -> FilterRows:send filtered data to further filter on rows
FilterRows -> EntityRelationFilter: Check primary and foreign key constraints to apply final filter
EntityRelationFilter -> USER: Return modified/ filtered data
@enduml