@startuml
title Release Automation Process

start
group RA-1: Trigerring the Process
    :User passes link to excel dictionary on OSF to use for the release;
    :User passes OSF personal access token;
    :User triggers release process;
end group

group RA-2: Creating the Release Files
    :Retrieve Excel Dictionary;
    :Parse metadata from files sheet;
    :Construct file names, ending in ".csv" or ".xlsx";
    :Populate file with information from appropriate sheet;
    :Add optional headers;
    :Store file in appropriate directory based on its upload location;
end group

group RA-3: Deploying the files to GitHub
    :Check if previous release exists on GitHub in the appropriate directory;

    if (No previous release on GitHub) then (yes)
        :Create new release branch and move files to the GitHub file storage directory;
    else (no)
        if (Previous release is newer) then (yes)
            :Stop process and throw an error;
            stop
        else (no)
            :Move old files to archive directory and move new files to appropriate directory;
        endif
    endif
    :Create PR from release branch to dev branch;
end group
group RA-4: Deploying the files to OSF
    repeat
        :Check release status on GitHub;
    repeat while(Release branch is merged to main) is (no)
        ->yes;
    :Check if previous release exists on OSF;

    if (No previous release on OSF) then (yes)
        :Push files in the OSF release directory to OSF using user OSF key;
    else (no)
        if (Previous release is newer) then (yes)
            :Stop process and throw an error;
            stop
        else (no)
            if (Previous release is same version) then (yes)
                :Replace old files with new files on OSF;
            else (no)
                :Move old files to archive folder;
                :Push files in the OSF release directory to OSF using user OSF key;
            endif
        endif
    endif
end group

:Trigger workflow in PHES-ODM-Doc Repo;
note right: RA-5: Trigger a PR in the PHES-ODM-Doc repo

:Trigger workflow in PHES-ODM-Validation Repo;
note right: RA-6: Trigger a PR in the PHES-ODM-Validation repo
stop
@enduml