@startuml
title Release Automation Process

start
group RA-1: Trigerring the Process
    :User passes link to excel dictionary on OSF to use for the release;
    :User passes OSF personal access token;
    :User triggers release process;
end group

group RA-2: Creating the Release Files
    :Retrieve Excel Dictionary;

    :Parse metadata from files sheet;

    :Construct file names;

    :Fill file content;

    :Add optional headers;
end group

group RA-3: Deploying the files to GitHub
    :Check if previous release exists on GitHub;

    if (No previous release on GitHub) then (yes)
        :Create new release branch and files on GitHub;
    else (no)
        if (Previous release is newer) then (yes)
            :Stop process and throw an error;
            stop
        else (no)
            :Move old files and create new files on GitHub;
        endif
    endif
    :Create PR from release branch to dev branch;
end group
group RA-4: Deploying the files to OSF
    repeat
        :Check release status on GitHub;
    repeat while(Release branch is merged to main) is (no)
        ->yes;
    :Check if previous release exists on OSF;

    if (No previous release on OSF) then (yes)
        :Create new release files on OSF;
    else (no)
        if (Previous release is newer) then (yes)
            :Stop process and throw an error;
            stop
        else (no)
            if (Previous release is same version) then (yes)
                :Replace old files with new files on OSF;
            else (no)
                :Move old files to archive folder;
                :Create new release files on OSF;
            endif
        endif
    endif
end group

:Trigger workflow in PHES-ODM-Doc Repo;
note right: RA-5: Trigger a PR in the PHES-ODM-Doc repo

:Trigger workflow in PHES-ODM-Validation Repo;
note right: RA-6: Trigger a PR in the PHES-ODM-Validation repo
stop
@enduml